version: 2.1

orbs:
  gradle: circleci/gradle@1.0.11
  node: circleci/node@1.1.6
  node-build: substantial/node-build@2.3.0
  yarn: substantial/yarn@3.10.2
  codecov: codecov/codecov@1.0.5

jobs:

  junit:
    description: Run JUnit tests with Gradle and store reports
    executor: << parameters.executor >>
    parameters:
      executor:
        description: The name of custom executor to use
        type: executor
        default: gradle/gradle
      test_command:
        type: string
        default: test
      coverage_command:
        type: string
        default: jacocoTestReport
      test_results_path:
        description: Results to be published
        type: string
        default: build/test-results
      reports_path:
        description: Artifacts to be published
        type: string
        default: build/reports
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - run:
                name: Run Tests
                command: ./gradlew << parameters.test_command >>
            - run:
                name: JaCoCo Test Report
                command: ./gradlew << parameters.coverage_command >>
      - gradle/collect_test_results:
          test_results_path: <<parameters.test_results_path>>
          reports_path: <<parameters.reports_path>>
      - persist_to_workspace:
          root: build
          paths:
            - reports/*

  jest:
    description: |
      Run Jest tests with CRA scripts from Yarn and store reports
    executor: << parameters.executor >>
    parameters:
      executor:
        description: The name of custom executor to use
        type: executor
        default: node/default
    steps:
      - checkout
      - run:
          command: pwd
          working_directory: ~/project/src/main/frontend
      - run:
          command: ls -al
          working_directory: $CIRCLECI_WORKING_DIRECTORY/src/main/frontend

  codecov-jacoco-upload:
    description: Upload JaCoCo coverage on Codecov
    executor: << parameters.executor >>
    parameters:
      executor:
        description: The name of custom executor to use
        type: executor
        default: gradle/gradle
    steps:
      - checkout
      - gradle/with_cache:
          steps:
            - attach_workspace:
                at: build
            - run: curl -s https://codecov.io/bash | bash

workflows:
#  backend:
#    jobs:
#      - junit
#      - gradle/run:
#          name: ktlint
#          command: ktlintCheck
#      - codecov-jacoco-upload:
#          name: codecov
#          requires:
#            - junit
  frontend:
    jobs:
      - jest
