version: 2.1

orbs:
  gradle: circleci/gradle@1.0.11
  node: circleci/node@1.1.6

jobs:
  build-node:
    executor:
      name: node/default
      working_directory: ~/src/main/frontend
      tag: '10.4'
    steps:
      - pwd
      - ls -al
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run: yarn test

workflows:
  backend:
    jobs:
      - gradle/test
      - gradle/run:
          command: build -x test
  frontend:
    jobs:
      - build-node
