version: 2

jobs:
  fetch-backend:
    docker:
      - image: "circleci/openjdk:8-jdk-node-browsers"
    steps:
      - checkout
      - run:
          name: Fetch Gradle dependencies
          command: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-repo-v1-{{ .Branch }}-{{ checksum "dependencies.lockfile" }}
  build-backend:
    docker:
      - image: "circleci/openjdk:8-jdk-node-browsers"
    steps:
      - restore_cache:
          keys:
            - gradle-repo-v1-{{ .Branch }}-{{ checksum "dependencies.lockfile" }}
            - gradle-repo-v1-{{ .Branch }}-
            - gradle-repo-v1-
      - run:
          name: Build backend with Gradle
          command: ./gradlew build
  check-backend:
    docker:
      - image: "circleci/openjdk:8-jdk-node-browsers"
    steps:
      - restore_cache:
          keys:
            - gradle-repo-v1-{{ .Branch }}-{{ checksum "dependencies.lockfile" }}
            - gradle-repo-v1-{{ .Branch }}-
            - gradle-repo-v1-
      - run:
          name: Analyze backend code
          command: ./gradlew check

workflows:
  version: 2
  backend:
    jobs:
      - fetch-backend
      - build-backend:
          requires:
            - fetch-backend
      - check-backend:
          requires:
            - fetch-backend
            - build-backend
