version: 2.1

orbs:
  gradle: circleci/gradle@1.0.11
  node: circleci/node@1.1.6

jobs:

workflows:
  backend:
    jobs:
      - gradle/test:
          test_results_path: build/test-results
          reports_path: build/reports
      - gradle/run:
          name: ktlint
          command: ktlintCheck
