version: 2.1

orbs:
  gradle: circleci/gradle@1.0.11
  node: circleci/node@1.1.6

jobs:
  local-info:
    executor:
      name: node/default
      working_directory: ~/src/main/frontend
      tag: '10.4'
    steps:
      - run: pwd
      - run: ls -al

workflows:
  backend:
    jobs:
      - local-info
      - gradle/test:
          test_results_path: build/test-results
          reports_path: build/reports
      - gradle/run:
          command: build -x test
